#!/bin/bash

# Author: Ryan Tompkins
# Date: 03/21/2019
# Description: Log rxstatus over USB one time, save in file

rm /home/debian/CommStatus_logs.txt
touch /home/debian/CommStatus_logs.txt

echo "unlogall" > /dev/ttyUSB0
echo "log rxstatus ontime 0.5" /dev/ttyUSB0
