#!/bin/bash

# Author: Ryan Tompkins
# Date: 03/20/2019
# Description: Poll CAN port using rxstatus, store results in file, then use this to see if CAN works

rm /home/debian/CommStatus_logs2.txt
touch /home/debian/CommStatus_logs2.txt

echo "unlogall ccom1" > /dev/ttyO2
sleep 2s
echo "log ccom1 rxstatus ontime 1" > /dev/ttyO2

echo 5
( candump can0 ) > /home/debian/CommStatus_logs2.txt
